export const promoSliderCards = [
  {
    id: 1,
    title: "Давайте знакомиться",
    description: "Видеоролик расскажет о том, как мы работаем.",
    link: "Смотреть",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "0, 199, 33",
    color: "255, 255, 255",
  },
  {
    id: 2,
    title: "Онлайн вечеринка с Mars!",
    description: "Скидка -20% на любимые бренды!",
    link: "Присоединиться!",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "132, 9, 227",
    color: "255, 255, 255",
  },
  {
    id: 3,
    title: "Утро. Новости. Премьера.",
    description: "Новые сорта Ламбера!",
    link: "Купить!",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "249, 189, 89",
    color: "255, 255, 255",
  },
  {
    id: 4,
    title: "БЕСПЛАТНАЯ ДОСТАВКА!",
    description: "Средства по уходу за собой",
    link: "Получить",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "1, 191, 217",
    color: "255, 255, 255",
  },
  {
    id: 4,
    title: "Почувствуйте лето вместе с Lipton Ice Tea",
    description: "Новые дизайны классических вкусов",
    link: "Попробовать!",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "245, 152, 220",
    color: "0, 0, 0",
  },
  {
    id: 5,
    title: "Новинки от Агуши!",
    description:
      "Порадуйте малыша полезными фруктовыми батончиками и мини-хлебцами!",
    link: "Перекусить",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "255, 147, 5",
    color: "255, 255, 255",
  },
  {
    id: 6,
    title: "Щедрые выходные!",
    description: "Скидки до 50% с 30 июля по 2 августа!",
    link: "В каталог",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "52, 219, 213",
    color: "255, 255, 255",
  },
  {
    id: 7,
    title: "Фруктовая корзина",
    description: "Витамины для вас!",
    link: "Купить в один клик",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "43, 194, 68",
    color: "255, 255, 255",
  },
  {
    id: 8,
    title: "Большая упаковка",
    description: "Вода, соки и напитки в больших упаковках",
    link: "Посмотреть",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "93, 152, 240",
    color: "255, 255, 255",
  },
  {
    id: 9,
    title: "Рецепты",
    description: "Готовьте ваши любимые блюда вместе с нами!",
    link: "Посмотреть",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "115, 191, 57",
    color: "255, 255, 255",
  },
  {
    id: 10,
    title: "Освежись с Heineken 0.0!",
    description: "100% вкуса и 0% алкоголя",
    link: "Купить!",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "49, 46, 110",
    color: "255, 255, 255",
  },
  {
    id: 11,
    title: "Доставим на дачу!",
    description: "В пределах московского малого кольца",
    link: "К покупкам",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "167, 242, 17",
    color: "0, 0, 0",
  },
  {
    id: 12,
    title: "Персональный шопер",
    description:
      "Оформите заказ, и мы соберем корзину так же, как это сделали бы вы сами!",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "160, 128, 194",
    color: "255, 255, 255",
  },
  {
    id: 13,
    title: "Подарочные сертификаты",
    description: "Подарите сертификат на покупку в Сбермаркете своим близким!",
    link: "Подарить",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "156, 12, 60",
    color: "255, 255, 255",
  },
  {
    id: 14,
    title: "Скоро в школу!",
    description: "Покупайте все необходимые товары к школе",
    link: "Посмотреть",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "255, 165, 0",
    color: "255, 255, 255",
  },
  {
    id: 15,
    title: "Начни здоровый образ жизни!",
    description: "Мы выбрали для тебя только самое полезное!",
    link: "Посмотреть!",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "38, 150, 43",
    color: "255, 255, 255",
  },
  {
    id: 16,
    title: "Набор Радости от Mars",
    description:
      "Узнай как подсластить жизнь своим близким и сделать приятный подарок",
    link: "Выбрать подарок!",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "255, 182, 241",
    color: "52, 24, 108",
  },
  {
    id: 17,
    title: "Овощная корзина",
    description: "Витамины для вас!",
    link: "Купить в один клик",
    img: "https://via.placeholder.com/100x100?img=img",
    bgImage: "https://sbermarket.ru/static/promo_cards/background.png",
    bgColor: "235, 116, 56",
    color: "255, 255, 255",
  },
];

export const forSelection = [
  {
    id: 1,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "METRO",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "SELGROS",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Лента",
  },
  {
    id: 4,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ВкусВилл",
    text: "Доступно за 30 минут в Москве",
  },
  {
    id: 5,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Ашан",
  },
  {
    id: 6,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Азбука Вкуса",
    text: "Доступно за 30 минут в Москве",
  },
  {
    id: 7,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "МЕГАМАРТ",
  },
  {
    id: 8,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Бахетле",
  },
  {
    id: 9,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ВИКТОРИЯ",
  },
  {
    id: 10,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ЗЕЛЕНОЕ ЯБЛОКО",
  },
  {
    id: 11,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Аллея",
  },
  {
    id: 12,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Командор",
  },
  {
    id: 13,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "BILLA",
  },
  {
    id: 14,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "REAL",
  },
  {
    id: 15,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ДЕЯ",
  },
  {
    id: 16,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Хороший",
  },
  {
    id: 17,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ТИТАН",
  },
  {
    id: 18,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "СЕДЬМАЯ СТОЛИЦА",
  },
  {
    id: 29,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Забакальский Привозъ",
  },
  {
    id: 20,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "КИТ",
  },
  {
    id: 21,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ПАРУС",
  },
  {
    id: 22,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "КАРАВАН",
  },
  {
    id: 23,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "МАГНОЛИЯ",
  },
  {
    id: 24,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ВЕГА",
  },
  {
    id: 25,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Шан",
  },
  {
    id: 26,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "АУТЛЕТ",
  },
  {
    id: 27,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Осень",
  },
  {
    id: 28,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: 'ТЦ "Новомаринский"',
  },
  {
    id: 29,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "УДАЧНАЯ ПОКУПКА",
  },
  {
    id: 30,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ТД ХОРОШИЙ",
  },
  {
    id: 31,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ФРЕШ25",
  },
  {
    id: 32,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ТЦ SТОЛИЦА",
  },
  {
    id: 33,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "СИГМА",
  },
  {
    id: 34,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "ИДЕЯ",
  },
  {
    id: 35,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Столичный",
  },
  {
    id: 36,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "СберМаркет",
    text: "СберМаркет",
  },
  {
    id: 37,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Быстроном",
  },
  {
    id: 38,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "АГРОКОМПЛЕКС",
  },
  {
    id: 39,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "YVES ROCHER",
  },
  {
    id: 40,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Юг Опт",
  },
  {
    id: 41,
    image: "https://via.placeholder.com/70x70?text=Text",
    title: "Дочки-Сыночки",
  },
];

export const homePageImage = "https://via.placeholder.com/1245x518?text=Text";

export const getProduct = {
  brand: "Бренды ЛЕНТЫ",
  products: "Продукты питания",
  category: "Сладости",
  image: "https://via.placeholder.com/300x200?text=Text",
  name: "Конфеты Dolce Albero из горького шоколада с цельным лесным орехом",
  weight: "200 г",
  price: "252,69 ₽",
  presence: "Товара много",
  button: "Купить",
};

export const getRecommended = [
  {
    image: "https://via.placeholder.com/70x70?text=Text",
    price: "269.59 ₽",
    productName: "Конфеты Россия Щедрая душа Родные просторы с начинкой",
    weight: "190 г",
  },
  {
    image: "https://via.placeholder.com/70x70?text=Text",
    price: "252.69 ₽",
    productName: "Конфеты Dolce Albero Ассорти",
    weight: "200 г",
  },
  {
    image: "https://via.placeholder.com/70x70?text=Text",
    price: "115.79 ₽",
    productName: "Конфеты Бабаевский оригинальные с фундуком и какао",
    weight: "200 г",
  },
  {
    image: "https://via.placeholder.com/70x70?text=Text",
    price: "105.29 ₽",
    productName: "Миска Mallony 1,1л",
    weight: "1 шт",
  },
  {
    image: "https://via.placeholder.com/70x70?text=Text",
    price: "168.49 ₽",
    productName: "Миска Mallony 3,3л",
    weight: "1 шт",
  },
  {
    image: "https://via.placeholder.com/70x70?text=Text",
    price: "105.29 ₽",
    productName: "Грибы вешенки свежие",
    weight: "300 гр",
  },
];

export const getSpecification = {
  op: "Описание",
  spec: "Шоколадные конфеты Dolce Albero на каждый день к чаю.",
  value: "Пищевая ценность",
  weight: "на 100 г",
  protein: "Белки",
  weightProtein: "6,8 г",
  fat: "Жиры",
  weightFat: "37,9 г",
  carbohydrates: "Углеводы",
  weightCarbohydrates: "46,5 г",
  calories: "Калорийность",
  weightCalories: "549 ккал",
  item_1: "Состав",
  composition:
    'Сахар, какао тертое, жир специального назначения (пальмовое масло, пальмоядрогвое масло, эмульгатор лецитин соевый), ядра ореха фундука (лесного ореха) обжаренные, масло какао, какао-порошок, ядра ореха фундука (лесного ореха) обжаренные тертые, молоко сухое цельное, молоко сухое обезжиренное, эмульгатор лецитин соевый, ароматизаторы: "Ванилин", "Фундук", антиокислитель аскорбановая кислота.',
  info: "Общая информация",
  brand: "Бренд",
  dolce: "Dolce Albero",
  manufacturer: "Производитель",
  lenta: "Лента",
  country: "Страна",
  russia: "Россия",
  storageСonditions: "Условия хранения",
  terms:
    "При температуре от +15°C до +21°C и относительной влажности воздуха не более 75%",
  term: "Срок хранения",
  month: "9 мес",
  kindOfCandy: "Вид конфет",
  chocolate: "Шоколад",
  typeOfChocolate: "Вид шоколада",
  bitter: "Горький",
  flavor: "Вкус",
  walnut: "Ореховый",
  supplements: "Добавки",
  hazelnut: "Фундук",
  feature: "Особенность",
  glazed: "Глазированные",
  packaging: "Упаковка",
  box: "Картонная коробка",
  hideInformation: "Скрыть подробную информацию",
};

export const info = "С этим смотрят";
